services:
  postgres:
    image: postgres:15
    container_name: professores_postgres
    environment:
      POSTGRES_DB: professores_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: professores_api
    environment:
      DATABASE_URL: postgresql://postgres:postgres123@postgres:5432/professores_db
      DEBUG: "true"
      AUTO_CREATE_TABLES: "true"
      CREATE_DEFAULT_ADMIN: "true"
      DEFAULT_ADMIN_USERNAME: "admin"
      DEFAULT_ADMIN_PASSWORD: "admin123"
      DEFAULT_ADMIN_EMAIL: "admin@example.com"
      ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:3033,http://127.0.0.1:3000,https://edu.gsuave.site,http://edu.gsuave.site"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server:/app

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://apiedu.gsuave.site
    container_name: professores_web
    environment:
      #*NEXT_PUBLIC_API_URL: http://localhost:8000
      NEXT_PUBLIC_API_URL: http://apiedu.gsuave.site
      API_URL_INTERNAL: http://api:8000
      API_REWRITE_TARGET: http://api:8000
    ports:
      - "3033:3000"
    depends_on:
      - api

  proxy:
    image: nginx:alpine
    container_name: professores_proxy
    depends_on:
      - api
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8088:80"

volumes:
  postgres_data:
